source 'https://ioscocoa:111111@scm.instinctools.ru/scm/git/cocoapods.specs'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

def mainpods
  pod "DLS-SWAPIServices", :path => "../"
end

target 'DLS-SWAPIServices_Example' do
  mainpods
end

target 'DLS-SWAPIServices_Tests' do
  mainpods	

  pod 'Specta'
  pod 'Expecta'
end


